Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tqdm import tqdm

from IPython import get_ipython
from IPython.display import display

Importing Images

In [ ]:
image_labels = [
    0, # Label for /content/1.jpg
    1, # Label for /content/10.jpg
    2, # Label for /content/100.jpg
    0, # Label for /content/10001.jpg (example, change as needed)
    1, # Label for /content/10003.jpg (example, change as needed)
    2, # Label for /content/10006.jpg (example, change as needed)
    0  # Label for /content/10022.jpg (example, change as needed)
]

IMG_SIZE = 64
data = []
labels = []

for i, img_path in enumerate(tqdm(image_paths)):
    try:
        img_array = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img_array is not None:
            resized = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
            data.append(resized.flatten())
            labels.append(image_labels[i])

    except Exception as e:
        print(f"Error loading image {img_path}: {e}")
        pass

data = np.array(data)
labels = np.array(labels)

print("Image loading complete.")
print(f"Number of images loaded: {len(data)}")
print(f"Number of labels loaded: {len(labels)}")

100%|██████████| 7/7 [00:00<00:00, 815.13it/s]

Image loading complete.
Number of images loaded: 7
Number of labels loaded: 7


In [ ]:
data = np.array(data)
labels = np.array(labels)

Training & Testing data

In [ ]:
X = data
y = labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print("Data splitting complete.")
print(f"Training set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")

Data splitting complete.
Training set size: 5 samples
Testing set size: 2 samples


SVM Model

In [ ]:
model = SVC(kernel='linear')

print("Training SVM model...")
model.fit(X_train, y_train)

print("SVM model training complete.")

Training SVM model...
SVM model training complete.


Evaluating SVM Model

In [ ]:
y_pred = model.predict(X_test)

Calculating Accuracy

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on the test set: {accuracy:.4f}")

Accuracy on the test set: 0.5000


Classification Report

In [ ]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00         1
           2       0.00      0.00      0.00         0

    accuracy                           0.50         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

Confusion Matrix

In [ ]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[0 0 1]
 [0 1 0]
 [0 0 0]]
